name: sui_shinami
description: "This package is developed for integration Shinami SDK for Sui."
version: 1.0.0
repository: "https://github.com/chyiiiiiiiiiiii/sui_shinami/tree/main"

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

  sui: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
